# Generated by Django 5.2.1 on 2025-05-28 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=18, help_text='Возраст должен быть от 14 до 120 лет', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(120)], verbose_name='Возраст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким номером телефона уже существует.'}, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
    ]
