# Generated by Django 5.2.1 on 2025-05-28 19:42

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_age_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='Europe/Minsk', max_length=50, verbose_name='Часовой пояс'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(help_text='Возраст должен быть от 18 до 120 лет', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким номером телефона уже существует.'}, max_length=19, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+375 (29) XXX-XX-XX'", regex='^\\+375 \\((?:29|33|44|25)\\) [0-9]{3}-[0-9]{2}-[0-9]{2}$')], verbose_name='Телефон'),
        ),
    ]
