# Generated by Django 5.2.1 on 2025-05-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Покупатель'), ('staff', 'Работник')], default='customer', max_length=10, verbose_name='Роль'),
        ),
    ]
