# Generated by Django 5.2.1 on 2025-05-28 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('str_repr', models.CharField(blank=True, max_length=300, verbose_name='Строковое представление')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название жанра')),
                ('str_repr', models.CharField(blank=True, max_length=300, verbose_name='Строковое представление')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название языка')),
                ('str_repr', models.CharField(blank=True, max_length=300, verbose_name='Строковое представление')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('summary', models.TextField(verbose_name='Краткое содержание')),
                ('imprint', models.CharField(max_length=200, verbose_name='Издательство')),
                ('ISBN', models.CharField(max_length=13, verbose_name='ISBN')),
                ('str_repr', models.CharField(blank=True, max_length=300, verbose_name='Строковое представление')),
                ('author', models.ManyToManyField(related_name='books', to='books.author', verbose_name='Авторы')),
                ('genre', models.ManyToManyField(to='books.genre', verbose_name='Жанры')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=32, unique=True, verbose_name='Уникальный идентификатор')),
                ('due_back', models.DateField(blank=True, null=True, verbose_name='Дата возврата')),
                ('status', models.CharField(blank=True, choices=[('m', 'На обслуживании'), ('o', 'Выдана'), ('a', 'Доступна'), ('r', 'Зарезервирована')], default='m', max_length=1, verbose_name='Статус')),
                ('str_repr', models.CharField(blank=True, max_length=300, verbose_name='Строковое представление')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='books.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Экземпляр книги',
                'verbose_name_plural': 'Экземпляры книг',
                'ordering': ['due_back'],
            },
        ),
    ]
