# Generated by Django 5.2.1 on 2025-05-28 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_restriction',
            field=models.IntegerField(default=0, help_text='Возрастное ограничение (0-21)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)]),
        ),
    ]
