# Generated by Django 4.2.11 on 2025-05-28 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_book_quantity_purchasehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasehistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'История покупок', 'verbose_name_plural': 'История покупок'},
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('delivery', 'Доставка')], default='pickup', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='books.book'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
